# Generated by Django 3.1.7 on 2021-04-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_employer_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='accept_handicapped',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
