# Generated by Django 3.1.7 on 2021-05-05 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_employer_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
