# Generated by Django 3.1.7 on 2021-05-05 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_employer_dashboard', '0002_joblisting_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='is_active',
            field=models.CharField(default='Active', max_length=10),
        ),
    ]
