# Generated by Django 3.1.7 on 2021-04-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_employer_dashboard', '0002_joblisting_accept_handicapped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='accept_handicapped',
            field=models.CharField(choices=[('2', 'NO'), ('1', 'YES')], max_length=3),
        ),
    ]
