# Generated by Django 3.1.7 on 2021-04-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_employer_dashboard', '0002_auto_20210414_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='application_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='contract_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
