# Generated by Django 3.1.7 on 2021-04-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_employer_dashboard', '0003_auto_20210410_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='accepted_handicapped_types',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='accept_handicapped',
            field=models.CharField(max_length=3),
        ),
    ]
