# Generated by Django 3.1.7 on 2021-04-14 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_employer_dashboard', '0003_auto_20210414_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='benefits',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='job_schedules',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='qualification_experience_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='qualification_languages',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='qualification_licenses',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='qualification_minimum_education_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='supplemental_pay',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
