# Generated by Django 3.1.7 on 2021-05-06 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_employer_dashboard', '0003_auto_20210505_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='is_active',
            field=models.CharField(blank=True, default='Active', max_length=10, null=True),
        ),
    ]
