# Generated by Django 3.1.7 on 2021-04-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_employer_dashboard', '0004_auto_20210410_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='accepted_handicapped_types',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
