# Generated by Django 3.1.7 on 2021-04-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_employer_dashboard', '0004_auto_20210414_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='application_resume',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='benefits',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='contract_type',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='job_schedules',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='qualification_experience_type',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='qualification_languages',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='qualification_licenses',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='qualification_minimum_education_level',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='supplemental_pay',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
