# Generated by Django 3.1.7 on 2021-05-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_employer_dashboard', '0004_auto_20210506_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblisting',
            name='qualification_education',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='qualification_experience',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='qualification_language',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='qualification_license',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='qualification_location',
        ),
        migrations.AddField(
            model_name='joblisting',
            name='qualifications',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
