# Generated by Django 3.1.7 on 2021-05-17 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_employer_dashboard', '0006_auto_20210515_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='date_posted',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
