# Generated by Django 3.1.7 on 2021-05-17 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_employer_dashboard', '0007_joblisting_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='date_posted',
            field=models.DateTimeField(auto_now=True, default=None),
            preserve_default=False,
        ),
    ]
