# Generated by Django 3.1.7 on 2021-04-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0003_auto_20210425_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autocomplete',
            name='data',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='autocomplete',
            name='field_name',
            field=models.CharField(max_length=50),
        ),
    ]
