# Generated by Django 3.1.7 on 2021-06-06 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_findjob', '0003_auto_20210606_2255'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together=set(),
        ),
    ]
