# Generated by Django 3.1.7 on 2021-06-22 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=30)),
                ('proficiency', models.CharField(max_length=30)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resume')),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Personalinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField()),
                ('place_of_birth', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('resident_address', models.CharField(max_length=100)),
                ('zip_code', models.IntegerField()),
                ('telephone_no', models.IntegerField()),
                ('cellphone_no', models.IntegerField()),
                ('civilstatus', models.CharField(max_length=30)),
                ('citizenship', models.CharField(max_length=30)),
                ('gsis_id_no', models.CharField(max_length=30)),
                ('pagibig_id_no', models.CharField(max_length=30)),
                ('philhealth_no', models.CharField(max_length=30)),
                ('sss_no', models.CharField(max_length=30)),
                ('tin', models.CharField(max_length=30)),
                ('spouse_name', models.CharField(max_length=200)),
                ('mother_name', models.CharField(max_length=200)),
                ('father_name', models.CharField(max_length=200)),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=30)),
                ('proficiency', models.CharField(max_length=30)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_level', models.IntegerField()),
                ('duration_year', models.CharField(blank=True, default=None, max_length=4, null=True)),
                ('duration_month', models.CharField(default=None, max_length=10, null=True)),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_title', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('specialization', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('industry', models.CharField(max_length=50)),
                ('position_level', models.CharField(max_length=50)),
                ('salary_currency', models.CharField(max_length=50)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('experience_description', models.TextField(blank=True, max_length=3500, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=100)),
                ('graduation_date', models.DateField()),
                ('qualification', models.CharField(max_length=50)),
                ('university_location', models.CharField(max_length=50)),
                ('field_of_study', models.CharField(max_length=50)),
                ('major', models.CharField(max_length=30)),
                ('grade', models.DecimalField(decimal_places=2, max_digits=3)),
                ('additional_information', models.TextField(max_length=3500)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
