# Generated by Django 3.1.7 on 2021-03-25 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_title', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('specialization', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('industry', models.CharField(max_length=50)),
                ('position_level', models.CharField(max_length=50)),
                ('salary_currency', models.CharField(max_length=50)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('experience_description', models.TextField(blank=True, max_length=1000, null=True)),
                ('applicant_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
