# Generated by Django 3.1.7 on 2021-03-25 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_applicant_portfolio', '0002_auto_20210325_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='experience_description',
            field=models.TextField(blank=True, max_length=3500, null=True),
        ),
    ]
