# Generated by Django 3.1.7 on 2021-03-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_applicant_portfolio', '0002_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
