# Generated by Django 3.1.7 on 2021-04-19 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_applicant_portfolio', '0005_auto_20210329_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='sample_field',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
