# Generated by Django 3.1.7 on 2021-04-19 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_applicant_portfolio', '0006_education_sample_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='sample_field',
        ),
    ]
