# Generated by Django 3.1.7 on 2021-03-26 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_applicant_portfolio', '0006_auto_20210326_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiencelevel',
            old_name='applicant_level',
            new_name='experience_level',
        ),
    ]
