# Generated by Django 3.1.7 on 2021-06-07 02:24

from django.db import migrations, models
import storages.backends.dropbox


class Migration(migrations.Migration):

    dependencies = [
        ('app_applicant_portfolio', '0007_remove_education_sample_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='resume',
            field=models.FileField(blank=True, null=True, storage=storages.backends.dropbox.DropBoxStorage(), upload_to='resume'),
        ),
    ]
