# Generated by Django 3.1.7 on 2021-05-19 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_applicant_portfolio', '0007_remove_education_sample_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personalinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('middlename', models.CharField(max_length=30)),
                ('birthday', models.DateField()),
                ('place_of_birth', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('resident_address', models.CharField(max_length=30)),
                ('zip_code', models.IntegerField(max_length=30)),
                ('telephone_no', models.IntegerField(max_length=30)),
                ('cellphone_no', models.IntegerField(max_length=30)),
                ('civilstatus', models.CharField(max_length=30)),
                ('citizenship', models.CharField(max_length=30)),
                ('gsis_id_no', models.CharField(max_length=30)),
                ('pagibig_id_no', models.CharField(max_length=30)),
                ('philhealth_no', models.CharField(max_length=30)),
                ('sss_no', models.CharField(max_length=30)),
                ('tin', models.CharField(max_length=30)),
                ('spouse_name', models.CharField(max_length=200)),
                ('mother_name', models.CharField(max_length=200)),
                ('father_name', models.CharField(max_length=200)),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
