# Generated by Django 3.1.7 on 2021-05-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_applicant_portfolio', '0008_personalinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='middlename',
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='resident_address',
            field=models.CharField(max_length=100),
        ),
    ]
