# Generated by Django 3.1.7 on 2021-03-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_applicant_portfolio', '0009_auto_20210326_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencelevel',
            name='duration_month',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
