# Generated by Django 3.1.7 on 2021-05-19 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_applicant_portfolio', '0009_auto_20210520_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='cellphone_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='telephone_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='zip_code',
            field=models.IntegerField(),
        ),
    ]
