# Generated by Django 3.1.7 on 2021-03-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_applicant_portfolio', '0010_experiencelevel_duration_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencelevel',
            name='duration_month',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
