# Generated by Django 3.1.7 on 2021-03-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_applicant_portfolio', '0012_auto_20210326_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencelevel',
            name='duration_month',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
