# Generated by Django 3.1.7 on 2021-03-28 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_applicant_portfolio', '0013_auto_20210326_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=30)),
                ('graduation_date', models.DateField()),
                ('qualification', models.CharField(max_length=30)),
                ('university_location', models.CharField(max_length=30)),
                ('field_of_study', models.CharField(max_length=30)),
                ('major', models.CharField(max_length=30)),
                ('grade', models.DecimalField(decimal_places=2, max_digits=3)),
                ('additional_information', models.TextField(max_length=3500)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
