# Generated by Django 3.1.7 on 2021-03-28 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_applicant_portfolio', '0014_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='field_of_study',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='education',
            name='major',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='education',
            name='qualification',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='education',
            name='university',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='education',
            name='university_location',
            field=models.CharField(max_length=50),
        ),
    ]
