# Generated by Django 3.1.7 on 2021-03-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_applicant_portfolio', '0015_auto_20210328_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='major',
            field=models.CharField(max_length=30),
        ),
    ]
