# Generated by Django 3.1.7 on 2021-04-15 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_employer_dashboard', '0005_auto_20210414_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joblisting',
            old_name='qualification_experience_type',
            new_name='qualification_education',
        ),
        migrations.RenameField(
            model_name='joblisting',
            old_name='qualification_languages',
            new_name='qualification_experience',
        ),
        migrations.RenameField(
            model_name='joblisting',
            old_name='qualification_licenses',
            new_name='qualification_language',
        ),
        migrations.RenameField(
            model_name='joblisting',
            old_name='qualification_minimum_education_level',
            new_name='qualification_license',
        ),
        migrations.RenameField(
            model_name='joblisting',
            old_name='qualification_education_required',
            new_name='qualification_location',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='qualification_experience_required',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='qualification_languages_required',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='qualification_license_required',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='qualification_location_required',
        ),
    ]
