# Generated by Django 3.1.7 on 2021-04-15 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_employer_dashboard', '0006_auto_20210415_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='qualification_location',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
