# Generated by Django 3.1.7 on 2021-04-15 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_employer_dashboard', '0007_auto_20210415_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='accepted_handicapped_types',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
